### ISSUE TITLE
gn_block problem

### ISSUE THREAD

**Issue by ICDI0906** [LeeDoYup/TGNet-keras#1]
Hi~, great work！ I have a question: what is the difference between gn_block and ordinary convolution layer?

**Comment by LeeDoYup** [comment]
Hello. Thank you for important question.
In the paper, you can see the graph networks to aggregate neighborhood features by permutational invariant operation (different from convolution.)
It is general concept, which can be applied into different tessellations from square to hexagon.
When we make the city into 2d grid image, the aggregation function can be easily implemented using mean pooling.
So, when we combine 1x1 convolution and 2d mean pooling layer, we can easily implement the graph networks without change of data structure.

**Comment by ICDI0906** [comment]
Thank you for the explanation!
